app_name: MyAwesomeAPI
port: 8080
database:
  type: sqlite
  name: ./data.db

authentication:
  type: jwt
  secret: mysupersecretkey
  token_expiration_minutes: 60
  
logging:
  enabled: true
  output: console # Pode ser "console" ou "file"
  file_path: logs/server.log

endpoints:
  - name: /users
    method: GET
    protected: true
    response:
      id: int
      name: string

  - name: /login
    method: POST
    request:
      username: string
      password: string
    response:
      token: string
