name: Build and Release

on:
  push:
    branches:
      - main # Sempre que houver um push na main

permissions:
  contents: write

jobs:
  build:
    name: Build binaries for all platforms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build binaries
        run: |
          mkdir -p bin
          GOOS=windows GOARCH=amd64 go build -o bin/gapizer-windows.exe
          GOOS=linux GOARCH=amd64 go build -o bin/gapizer-linux
          GOOS=darwin GOARCH=amd64 go build -o bin/gapizer-mac

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Get Current Date and Time
        id: datetime
        run: echo "::set-output name=datetime::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "auto-generated-main" # Tag fixa para identificar as releases automáticas da main
          artifacts: bin/*
          release_name: "Release - ${{ steps.datetime.outputs.datetime }}" # Nome com a data e hora
          body: |
            **Novos binários gerados automaticamente com as últimas mudanças:**
            - Windows: gapizer-windows.exe
            - Linux: gapizer-linux
            - macOS: gapizer-mac
          prerelease: true
