name: Build, Release, and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Debug: Verify package-lock.json
      - name: Verify package-lock.json
        run: Get-ChildItem -Path cli -Recurse

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: cli/package-lock.json

      # 4. Install Node.js dependencies
      - name: Install Node.js dependencies
        working-directory: cli
        run: npm ci

      # 5. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # 6. Build Go binary
      - name: Build Windows Binary
        run: go build -o bin/gapizer.exe ./src/main.go

      # 7. Build Windows Installer
      - name: Build Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer/gapizer_installer.iss
          options: /O+

      # 8. Debug Paths
      - name: Debug Paths
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing Installer Output Directory:"
          dir installer/Output

      # 9. Upload Installer as Artifact
      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gapizer-installer
          path: installer/Output/GAPIzer-Installer.exe

      # 10. Run semantic-release for versioning and npm publish
      - name: Run semantic-release
        working-directory: cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
