name: Build, Release, and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      # 3. Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci

      # 4. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # 5. Build Go binary
      - name: Build CLI and Go binary
        run: npm run build

      # 6. Build Windows Installer
      - name: Build Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer/gapizer_installer.iss
          options: /O+

      # 7. Debug Paths
      - name: Debug Paths
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing Installer Output Directory:"
          dir installer/Output

      # 8. Run semantic-release
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --debug --branch=main
