name: Build Windows Installer and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Windows Binary
        run: go build -o bin/gapizer.exe

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Create Output Directory
        run: mkdir Output

      - name: Debug All Files Before Build
        run: |
          echo "Listing all files and directories before building installer:"
          Get-ChildItem -Path . -Recurse

      - name: Build Windows Installer with Logs
        run: |
          "& 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' /O+ gapizer_installer.iss"
          echo "Inno Setup Build Completed"

      - name: Debug All Files After Build
        run: |
          echo "Listing all files and directories after building installer:"
          Get-ChildItem -Path . -Recurse

      - name: Check Installer File
        run: |
          if (!(Test-Path "Output\GAPIzer-Installer.exe")) {
            Write-Error "File not found: Output\GAPIzer-Installer.exe"
            exit 1
          }

      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gapizer-installer
          path: Output\GAPIzer-Installer.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Installer Artifact
        uses: actions/download-artifact@v4
        with:
          name: gapizer-installer

      - name: Generate Tag Name
        id: generate_tag
        run: echo "tag=auto-generated-main-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag }}
          artifacts: Output\GAPIzer-Installer.exe
          name: "GAPIzer Installer"
          body: |
            **Instalador gerado automaticamente com as últimas mudanças**
          prerelease: true
