name: Build Windows Installer and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Windows Binary
        run: go build -o bin/gapizer.exe

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Create Output Directory
        run: mkdir Output

      - name: Validate Binary in bin Directory
        run: |
          echo "Checking bin directory contents:"
          dir bin

      - name: Build Windows Installer with Logs
        run: |
          "& 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' /LOG=Output\build-log.txt gapizer_installer.iss"
          echo "Build log generated:"
          type Output\build-log.txt

      - name: Debug All Files After Build
        run: |
          echo "Listing all files and directories after building installer:"
          Get-ChildItem -Path . -Recurse

      - name: Check Installer File
        run: |
          if (!(Test-Path "Output\GAPIzer-Installer.exe")) {
            Write-Error "File not found: Output\GAPIzer-Installer.exe"
            exit 1
          }

      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gapizer-installer
          path: Output\GAPIzer-Installer.exe
